#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render a PR coverage comment.")
    parser.add_argument("--summary-json", required=True)
    parser.add_argument("--changed-files", required=True)
    parser.add_argument("--threshold-file", required=True)
    parser.add_argument("--output", required=True)
    return parser.parse_args()


def load_json(path: str) -> dict:
    return json.loads(Path(path).read_text())


def load_changed_files(path: str) -> list[str]:
    content = Path(path).read_text().splitlines()
    return [line.strip() for line in content if line.strip()]


def format_percent(value: float | None) -> str:
    if value is None:
        return "--"
    return f"{value:.1f}%"


def render_comment(summary: dict, changed_files: list[str], threshold: float) -> str:
    overall = float(summary["line_percent"])
    status = "pass" if overall >= threshold else "fail"
    icon = "✅" if status == "pass" else "❌"

    file_rows = []
    by_name = {item["filename"]: item for item in summary.get("files", [])}
    for path in changed_files:
        item = by_name.get(path)
        if item is None:
            continue
        file_rows.append(
            f"| `{path}` | {format_percent(item.get('line_percent'))} | "
            f"{format_percent(item.get('function_percent'))} | "
            f"{format_percent(item.get('branch_percent'))} |"
        )

    changed_section = ""
    if file_rows:
        changed_section = "\n".join(
            [
                "### Changed Files",
                "",
                "| File | Lines | Functions | Branches |",
                "| --- | ---: | ---: | ---: |",
                *file_rows,
            ]
        )
    else:
        changed_section = "### Changed Files\n\nNo changed engine/app files matched the coverage summary."

    return "\n".join(
        [
            "## Coverage Report",
            "",
            f"{icon} Status: {status}",
            "",
            f"- Line coverage: {format_percent(summary.get('line_percent'))}",
            f"- Function coverage: {format_percent(summary.get('function_percent'))}",
            f"- Branch coverage: {format_percent(summary.get('branch_percent'))}",
            f"- Threshold: {threshold:.1f}%",
            "",
            changed_section,
            "",
            "_Generated by the coverage gate workflow._",
            "",
        ]
    )


def main() -> int:
    args = parse_args()
    summary = load_json(args.summary_json)
    threshold_data = load_json(args.threshold_file)
    changed_files = load_changed_files(args.changed_files)
    content = render_comment(summary, changed_files, float(threshold_data["line"]))
    Path(args.output).write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
